mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home, register, reservation, reserv_table, create_table
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^register/', register),
    url(r'^reserve-bulktable/', reservation, name='reservation'),
    url(r'^Create-table/', create_table, name='create_table'),
    url(r'^reserve-table/', reserv_table, name='reserv_table'),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout),
    url(r'^', include('mysite.urls', namespace="mysite"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tables(models.Model):
	tabel_name = models.CharField(max_length=250, null=True, blank=True)
	tabel_capacity = models.IntegerField(null=True, blank=True)
	activeStatus = (
        (0, "created"),
        (1, "approved"),
    )
	status = models.IntegerField( choices= activeStatus, default=0, blank=True)
	image = models.ImageField(upload_to='profile_image', blank=True)
	def __unicode__(self):
		return self.tabel_name
	class Meta:
		verbose_name = "Table"
        verbose_name_plural = "Table"

class Reservations(models.Model):
	user_id = models.ForeignKey(User,null=True,blank=True)
	table_id = 	models.ForeignKey(Tables,null=True,blank=True)
	start_time = models.DateTimeField(auto_now_add=True)
	end_time = models.DateTimeField(auto_now_add=True)
	activeStatus = (
        (0, "created"),
        (1, "pending"),
        (2, "approved"),
    )
	reservation_status = models.IntegerField( choices= activeStatus, default=0, blank=True)
	def __unicode__(self):
		return self.table_id.tabel_name
	class Meta:
		verbose_name = "Reservation"
        verbose_name_plural = "Reservation"

mysite/forms.py
from django import forms
class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'Username',
        max_length = 32
    )
    email = forms.CharField(
        required = True,
        label = 'Email',
        max_length = 32,
    )
    password = forms.CharField(
        required = True,
        label = 'Password',
        max_length = 32,
        widget = forms.PasswordInput()
    )

mysite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django import forms
from .forms import UserRegistrationForm
from django.template import loader
from models import Tables, Reservations
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import datetime
from django.shortcuts import redirect 
# Create your views here.
def home(request):
    template_var = {}
    table = Tables.objects.all()
    reserv = Reservations.objects.all()
    template_var['table'] = table
    template_var['reserv'] = reserv
    return render(request, 'mysite/home.html', template_var)
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email =  userObj['email']
            password =  userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username = username, password = password)
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                raise forms.ValidationError('Looks like a username with that email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'mysite/register.html', {'form' : form})
@csrf_exempt
def reservation(request):
    table_id = str(request.POST['val'])
    now = datetime.datetime.now()
    now_plus_1 = now + datetime.timedelta(hours = 1)
    lis = []
    for x in table_id:
        if x != ',':
            lis.append(int(x))
    booking_tables = lis
    table = Tables.objects.all()
    user_id = request.POST['user_id']
    user = User.objects.get(id=user_id)
    for tab in booking_tables:
        for a in table:
            table_val = Tables.objects.get(id=a.id)
            if a.id == tab:
                Tables.objects.filter(id=a.id).update(status=1)
                Reservations.objects.create(user_id=user,table_id=table_val,reservation_status=0,start_time=now ,end_time=now_plus_1)
    return HttpResponse('success')

@csrf_exempt
def reserv_table(request):
    table_id = str(request.POST['val'])
    table_val = Tables.objects.get(id=table_id)
    user_id = request.POST['user_id']
    now = datetime.datetime.now()
    now_plus_1 = now + datetime.timedelta(hours = 1)
    user = User.objects.get(id=user_id)
    Tables.objects.filter(id=table_id).update(status=1)
    Reservations.objects.create(user_id=user,table_id=table_val,reservation_status=0,start_time=now ,end_time=now_plus_1)
    return HttpResponse('success')


def create_table(request):
    template_var = {}
    if request.method == "POST":
        print '--------------------------------'
        first_name = request.POST['username']
        last_name = request.POST['password']
        if first_name and last_name:
            Tables.objects.create(tabel_name=first_name, tabel_capacity=int(last_name), status=0)
            return redirect('mysite:home')
    print('=============================')
    return render(request, 'mysite/create_table.html', template_var)

mysite/templates/mysite/create_table.html
<html>
<body>

<h2>Create New Table</h2>

<form method="post" id="loginform" action="" novalidate onsubmit="return loginvalidate();">{% csrf_token %}
    <label>
        <span>Table Name</span>
        <input type="text" value="" name="username" id="username" class="floating-item-input input-item nokeyup-common">
    </label>
    <label>
        <p class='capacity'>Capacity</p>
        <input type="number" value="" name="password" id="password"  class="floating-item-input input-item nokeyup-common" >
    </label>            
        <button class="button greybg">Create Table</button>
</form>

</body>
</html>

<style type="text/css">
span{
    left: -94px;
    position: relative;
    top: -5px;
}
.capacity{
    position: relative;
    left: -104px;
    top: 25px;
}
form{
    text-align: center;
    margin-top: 50px;
}
h2{
    position: relative;
    left: 40%;
    margin-top: 100px;
}
.button{
    display: block;
    position: relative;
    left: 40%;
    margin-top: 20px;
}
#username{
    display: block;
    position: relative;
    left: 40%;
    width: 20%;
    height: 30px;
}
#password{
    display: block;
    position: relative;
    left: 40%;
    width: 20%;
    margin-top: 30px;
    height: 30px;
}

</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" src="js/script.js"></script>
<script type="text/javascript">

</script>

mysite/templates/mysite/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    {% if user.is_authenticated %}
    <p>hello</p>
    <p>welcome {{ user.username }}</p>
    <p><a href="/logout">Logout</a></p>
    {% else %}
    <p><a href="/login">Login</a></p>
    <p><a href="/register">Register</a></p>
    {% endif %}
</body>
</html>

mysite/templates/mysite/register.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/mysite/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    {% csrf_token %}
    {% if user.is_authenticated %}
    <p>Welcome {{ user.username }}</p>
    <h2>Welcome to Tamilnadu restaurant</h2>
    <a class='logout' href="/logout">Logout</a>
    {% if user.is_superuser %}
            <a class='createTable' href="/Create-table">Create Table</a>
    {% endif %} 
    <button class="btn" id="myBtn" value="{{ user.id }}">Book Now</button>	
    <div class='row-card'>
    {% for tab in table %}
    {% if table.count > 8 %}
    {% if tab.status == 0 %}
	    <div class="card">
		  <img class='image' src="/media/profile_image/ta.jpg" alt="Avatar" style="width:100%">
		  <div class="container">
		    <h4>Table Name :  <b>{{tab.tabel_name}}</b></h4> 
		    <p>Capacity :  {{tab.tabel_capacity}}</p> 
		  </div>
          <button class="book-btn" id="myBtn" value="{{tab.id}}">Book Now</button>
          <label class="time-label">Time</label>
          <input class="time" type="time" name="usr_time">
		</div>
    {% endif %} 
    {% endif %} 
	{% endfor %}
    {% for tab in reserv %}
    {% if tab.user_id.id == user.id %}
        <div class="card">
          <img class='image' src="/media/profile_image/ta.jpg" alt="Avatar" style="width:100%">
          <div class="container">
            <h4>This <b style="color:red">{{tab.table_id.tabel_name}}</b> table is booked</h4> 
            <p>Not Available for next one hour</p> 
          </div>
        </div>
    {% endif %}    
    {% endfor %}
	</div>	
    {% else %}
    <p><a href="/login">Login</a></p>
    <p><a href="/register">Register</a></p>
    {% endif %}
    <div id="myModal" class="modal">
	  <div class="modal-content">
	    <span class="close">&times;</span>
	    {% for tab in table %}
        {% if tab.status == 0 %}
	    	<div class="cblist">
			    <input type="checkbox" value="{{tab.id}}" id="cb{{ forloop.counter }}" /> <label for="cb{{ forloop.counter }}">{{tab.tabel_name}}</label>
			</div>
        {% endif %}    
	    {% endfor %}	
	  	<button class="confirm-btn">Confirm your table</button>
	  </div>
	</div>
</body>
</html>
<style>
.time{
    left: 45px;
    position: relative;
}
.time-label{
    position: relative;
    left: 40px;
    top: 3px;
}
.confirm-btn{
	position: relative;
	left: 60%;
    top: -10px;
}
.cblist{
	left: 40%;
    position: relative;
    padding: 10px;
    top: 20px;
}
.row-card{
	display: flex;
	flex-wrap: wrap;
	margin-left: 80px;
	margin-top: 100px;
}
.image{
	height: 250px;
}
.card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 20%;
    margin: 20px;
    padding: 10px;
    background-color: #f5f5f0;
}

.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}
.card:hover .image{
    opacity: 0.7;
}


.container {
    padding: 2px 16px;
}
.btn:hover {
    background-color: green;
    color: yellow;
}
.btn{
	position: absolute;
    top: 70px;
    right: 40px;
    padding: 14px;
    color: green;
    background-color: yellow;
    border-radius: 15px;
    border: 1px solid green;
}
.logout{
	position: absolute;
    top: 10px;
    right: 20px;
}
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
.book-btn{
    left: 15px;
    position: relative;
}
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" src="js/script.js"></script>
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
$(".confirm-btn").click(function(){
	var selectedTable = []
    var user_id = $('#myBtn').val();
    $('input[type=checkbox]').each(function () {
    	if(this.checked){
			var sThisVal = this.value
			selectedTable.push(sThisVal);
		}	
	});
	if ($("input[type='checkbox']:checked").length < 8){
    	alert('Atleast 8 table you should book');
    }
    else{
        $.ajax({
           type:"POST",
           url:"{% url "mysite:reservation" %}",
           data: {
                  'val': String(selectedTable),'user_id':user_id,
                  },
            beforeSend: function() {
                  
               },
            success: function(response){            
               
       }
   });
    }
});

$('.book-btn').click(function(){
    var time = $(this).parent().find('.time').attr('value')
    console.log(time)
    if(time==''){
        alert('please mention you time')
    }
    else{
    var selectedTable = $(this).attr('value');
    var user_id = $('#myBtn').val();
    $.ajax({
           type:"POST",
           url:"{% url "mysite:reserv_table" %}",
           data: {
                  'val': selectedTable, 'user_id':user_id,
                  },
            beforeSend: function() {
                  
               },
            success: function(response){            
               alert('Your table is booked Successfully');
               window.location.reload();
       }
   });
}
});

</script>

templates/mysite/register.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>